### ISSUE TITLE
Series9

### ISSUE THREAD

**Issue by A4K-Official** [a4k-openproject/script.module.openscrapers#65]
@nazegnl 
Series9 giving me this error on latest dev branch

Traceback (most recent call last):
  File "C:\Users\*\Documents\GitHub\script.module.openscrapers\lib\openscrapers\sources_openscrapers\en\series9.py", line 111, in sources
    url = self.searchMovie(data['title'], data['year'])
  File "C:\Users\*\Documents\GitHub\script.module.openscrapers\lib\openscrapers\sources_openscrapers\en\series9.py", line 93, in searchMovie
    url = [i[0] for i in results if cleantitle.get(i[1]) == cleantitle.get(title)][0]
IndexError: list index out of range

**Comment by bjbca** [comment]
No problem with series9 here, but my log cleared right up after removing:
cartoonwire
filmrls
library
moviesonline
primewire
watchfree1
guess i should have kept the log to show the errors....

**Comment by nazegnl** [comment]
@A4K-Official was focussing on episodes when testing the series9 one will have a look. Seems that it gets empty result from the API call.

**Comment by bjbca** [comment]
I was getting constant log error "best-moviez.ws - href:" so i removed bestmoviez, and still the error then i found code reference to best-moviez.ws - href: in
rlslog.py
movieswbb.py
so i removed them and all good now.

**Comment by nazegnl** [comment]
Can you please post the error then I will have a look :)

**Comment by bjbca** [comment]
This is it:
[2019-05-06 05:33:20] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:21] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:21] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:22] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:22] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:23] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:23] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:24] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 05:33:25] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href:

**Comment by nazegnl** [comment]
Those are debug logs, you zee that href is empty so it could not find anything. Just removed these debug log lines from the scrapers.

**Comment by nazegnl** [comment]
@A4K-Official and @bjbca I created discord room for the OpenScrapers.
https://discord.gg/sfDuQh

**Comment by bjbca** [comment]
Ok, sorry these post are getting off topic, just thought i would share this log for interest sake while we are at it, then im done, note i do have captchas dissabled, the log has been edited to hide my macs info etc.
[2019-05-06 19:41:10] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (403): http://watchfree1.com/search-movies/ray+donovan+season+5.html
[2019-05-06 19:41:10] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Library - Exception: 
Traceback (most recent call last):
/en/library.py", line 110, in sources
    r = json.loads(r)['result']['tvshows']
KeyError: 'tvshows'
[2019-05-06 19:41:20] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: filmrls.com - Exception: 
Traceback (most recent call last):
/en/filmrls.py", line 103, in sources
    html = self.scraper.get(url)
Kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
/modules/cfscrape.py", line 218, in solve_cf_challenge
    return self.request(method, redirect_url, **original_kwargs)
/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
/modules/cfscrape.py", line 205, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
/modules/cfscrape.py", line 145, in request
    raise Exception(exception_message)
Exception: Cloudflare returned captcha!
[2019-05-06 19:41:41] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (('The read operation timed out',)) => https://cartoonwire.to/episode/ray-donovan-season-5-episode-1/
[2019-05-06 19:41:48] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => http://moviesonline.gy/watch/ox1yj4xN-ray-donovan-season-5.html
[2019-05-06 19:42:05] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Library - Exception: 
Traceback (most recent call last):
/en/library.py", line 110, in sources
    r = json.loads(r)['result']['tvshows']
KeyError: 'tvshows'
[2019-05-06 19:42:05] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (403): http://watchfree1.com/search-movies/ray+donovan+season+6.html
[2019-05-06 19:42:09] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:09] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: filmrls.com - Exception: 
Traceback (most recent call last):
/en/filmrls.py", line 103, in sources
    html = self.scraper.get(url)
/Kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
/modules/cfscrape.py", line 205, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
/modules/cfscrape.py", line 145, in request
    raise Exception(exception_message)
Exception: Cloudflare returned captcha!
[2019-05-06 19:42:10] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:10] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:10] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:11] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => http://moviesonline.gy/watch/JdAWoNxL-ray-donovan-season-6.html
[2019-05-06 19:42:11] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:12] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:12] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:13] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:13] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:42:18] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (404): https://cartoonwire.to/episode/ray-donovan-season-6-episode-11/
[2019-05-06 19:42:57] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Library - Exception: 
Traceback (most recent call last):
/en/library.py", line 110, in sources
    r = json.loads(r)['result']['tvshows']
KeyError: 'tvshows'
[2019-05-06 19:42:57] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (403): http://watchfree1.com/search-movies/ray+donovan+season+5.html
[2019-05-06 19:43:01] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: filmrls.com - Exception: 
Traceback (most recent call last):
/en/filmrls.py", line 103, in sources
    html = self.scraper.get(url)
/Kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
/modules/cfscrape.py", line 205, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
/modules/cfscrape.py", line 145, in request
    raise Exception(exception_message)
Exception: Cloudflare returned captcha!
[2019-05-06 19:43:03] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => http://moviesonline.gy/watch/ox1yj4xN-ray-donovan-season-5.html
[2019-05-06 19:43:28] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (('The read operation timed out',)) => https://cartoonwire.to/episode/ray-donovan-season-5-episode-1/
[2019-05-06 19:43:48] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Library - Exception: 
Traceback (most recent call last):
/en/library.py", line 110, in sources
    r = json.loads(r)['result']['tvshows']
KeyError: 'tvshows'
[2019-05-06 19:43:48] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (403): http://watchfree1.com/search-movies/ray+donovan+season+6.html
[2019-05-06 19:43:51] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:52] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:52] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: filmrls.com - Exception: 
Traceback (most recent call last):
/en/filmrls.py", line 103, in sources
    html = self.scraper.get(url)
/Kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
/modules/cfscrape.py", line 205, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
/modules/cfscrape.py", line 145, in request
    raise Exception(exception_message)
Exception: Cloudflare returned captcha!
[2019-05-06 19:43:52] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:53] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:53] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:54] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:54] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => http://moviesonline.gy/watch/JdAWoNxL-ray-donovan-season-6.html
[2019-05-06 19:43:54] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:55] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:43:55] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: best-moviez.ws - href: 
[]
[2019-05-06 19:44:14] [COLOR red][ OPENSCRAPERS DEBUG ][/COLOR]: Request-Error (404): https://cartoonwire.to/episode/ray-donovan-season-6-episode-11/
